### ISSUE TITLE
保存しようとすると「グループを選択してください」と出る

### ISSUE THREAD

**Issue by hanachin** [yasslab/qiita-team-extension#11]
![2017-09-11 13 51 21](https://user-images.githubusercontent.com/167012/30258918-5814e54e-96f8-11e7-92be-318f80ec98dc.png)

**Comment by nalabjp** [comment]
safariとchromeのTampermonkeyだと再現しなかった（「グループを選択してください」の吹き出しが出ない）のでもう少し情報貰えると助かります。

@hanachin 
chrome extensionで使ってらっしゃるんでしたっけ？
環境再現したいんですが、お手元の環境を教えてもらえますか？（ユーザスクリプトのインストール方法が良くわからなかった🤔）

@himajin315 
safari, chrome以外のブラウザで使ってますか？

**Comment by himajin315** [comment]
@nalabjp ブラウザはChromeの最新を使ってます。
Google Chrome は最新版です
バージョン: 61.0.3163.79（Official Build） （64 ビット）

**Comment by hanachin** [comment]
Chromeで chrome://extensions/ を開いて、そこにドラッグ・アンド・ドロップでインストールしてます。Chromeのバージョン: 61.0.3163.79（Official Build） （64 ビット）です。
Tampermonkeyは使ってない感じです。

**Comment by nalabjp** [comment]
お二人ともありがとうございます！

chromeのTampermonkeyを無効にして、
> chrome://extensions/ を開いて、そこにドラッグ・アンド・ドロップ

こちらで試してみたんですが私の手元だと吹き出し出ないですね。
新規投稿、下書きからの編集、を試してみたんですが。

chromeも最新（61.0.3163.79（Official Build） （64 ビット））になっているのを確認したので、
あと差異があるのはなんだろう？🤔

（`DEFAULT_OPTION_VALUE`の値はdebug, confidentialのどちらでも意図した動きになりました）

**Comment by hanachin** [comment]
確認ありがとうございます。インストールしなおして再確認します 🙆‍♂️

**Comment by hanachin** [comment]
他に入れてる拡張が邪魔をしているのかも、と思ってこの2つだけ有効にしてシークレットウィンドウで試してみたんですが、やっぱりエラーが出ますね。

![2017-09-11 15 46 17](https://user-images.githubusercontent.com/167012/30261601-5f849940-9708-11e7-9d7f-312f144eac71.png)

ここのselectボックス、JSで組み立ててそうなのでもしかしたらマシンのスペックによって実行のタイミングが変わるのかも...?

**Comment by yasulab** [comment]
僕も手元の Tampermonkey で試してみました。結果は次のような形です:

- デフォルト (指定グループ+共同編集モード) で投稿ボタンを押下 => グループを選択してください
- 指定グループ+下書き保存で投稿ボタンを押下 => 成功
- 指定グループ+個人投稿モードで投稿ボタンを押下 => グループを選択してください
- 指定グループを「デフォルト→全体に公開→指定グループ」の順に選んだ後に投稿ボタンを押下 => 成功


環境:

- Chrome: Version 60.0.3112.113 (Official Build) (64-bit)
- Tampermonkey: v4.3.6
- 使っているスクリプト: 
   - https://github.com/yasslab/qiita-team-extensions/blob/7940524398f9cb841e38c791b3c4f6edeb087d08/co_editing_mode.user.js
   - https://github.com/yasslab/qiita-team-extensions/blob/7940524398f9cb841e38c791b3c4f6edeb087d08/default_group.user.js

**Comment by hanachin** [comment]
共同編集モードじゃなかったらいけるのかな...`co_editing_mode.user.js`無効にして試してみます

**Comment by hanachin** [comment]
`co_editing_mode.user.js`無効にしても同じですね。

@yasulab ブラウザのバージョン古いのでアップデートした方が良さそうです

**Comment by nalabjp** [comment]
なるほど、ごめんなさい、僕の検証がちょっと足りてなかったようですね。
下書きだと問題ないけど、投稿にすると吹き出しが出るんですね、再現しました。

**Comment by yasulab** [comment]
おぉ、再現したようでよかったです! 😸

**Comment by yasulab** [comment]
こちらの件、Qiita:Team の中の人が対応されているようなので、そのうち直っていそうですね ;)

> Qiita:Team で所属グループがないと、新規作成時にセレクトボックスを「空白」から「全体に公開」に変更しないと投稿できない件、直らないということは意図した仕様？マジか。 

--------------------

> いつもありがとございます。こちらIssueを立てていて対応予定になっています。お手数おかけしますがよろしくお願いします🙇 
> https://twitter.com/QiitaTeam/status/907582729847398402

**Comment by yasulab** [comment]
> こちらの件、Qiita:Team の中の人が対応されているようなので、そのうち直っていそうですね ;)

んー、先ほど試してみたけど、まだ同じ状況のようですね 😓💦 
<img width="448" alt="screen shot 2017-09-25 at 11 13 29" src="https://user-images.githubusercontent.com/155807/30789775-bc86dba0-a1e2-11e7-827f-7f82a3aa3f3f.png">

**Comment by yasulab** [comment]
まだ直ってない 🤔💭

**Comment by yasulab** [comment]
## 現状

- セレクトボックスを選択する方法がいくつかある
- いずれも選択したことにならなかった (nalabjp さんが試してくれた)
- 裏側が React でイベントの伝搬がうまくいってなさそう

**Comment by yasulab** [comment]
こちらの Issue、次のイベントで直接聞いてこようと思います 🏃💨
http://peatix.com/event/316733
[<img width="396" alt="qiita-team-event" src="https://user-images.githubusercontent.com/155807/31979906-1f75349c-b984-11e7-9a3f-52530bc0f01e.png">](https://www.facebook.com/yaotti/posts/10155315919759039?comment_id=10155315946274039&reply_comment_id=10155315948089039&comment_tracking=%7B%22tn%22%3A%22R1%22%7D)

**Comment by yasulab** [comment]
@nanophate が直してくれました! Thx! 👏
