### ISSUE TITLE
Tampermonkey で環境変数みたいな情報を扱いたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/qiita-team-extension#2]
https://github.com/yasslab/qiita-team-extension/blob/8ff1c7c6eefb82bb846d7f98f5e119c23d86aab0/default_group.user.js#L14

`debug` を環境変数 (`ENV['GROUP_ID']`) にして、環境変数経由でグループのデフォルト値を操作できると楽そうですが、Tampermonkey はブラウザにインストールするタイプのツールなので、さすがに難しそうかなぁ🤔

**Comment by yasulab** [comment]
(あれ、行を指定してコードをコピペするとこういう風に表示されるんだ🤔 知らなかった 💦 )

<img width="611" alt="github_code-snippet" src="https://user-images.githubusercontent.com/155807/29955803-5f67c6fa-8f1d-11e7-9b25-59ec3002c8e3.png">

**Comment by nalabjp** [comment]
http://tampermonkey.net/documentation.php?ext=dhdg#GM_setValue

local strage(?)を読み書きするインタフェースはあるんですけど、
そこを更新するモノを作らないといけないからちょっと違うんですよねー。
File APIとか使えないかな？
ちょっと調べてみますね。

**Comment by yasulab** [comment]
ありがとうございます! 🙏

**Comment by nalabjp** [comment]
File APIとFileSystem APIを勘違いしていたみたいですが、これは無理そうですね。

ローカルファイルについては、
Tampermonkeyが提供する`@require`で読むことはできるんですが、chromeは動くけどsafariはダメっぽいのでブラウザに依存しそうです。
あと、ファイルパスを絶対パスで指定することになるので、homeディレクトリが使えなさそうでどこに置こうかなぁ？という感じもしますね🤔

別の方法として以下のような設定を見つけたのでユーザごとに任意のjsファイルをincludeさせるというのは使えるかもしれませんね。
![2017-09-01 23 35 11](https://user-images.githubusercontent.com/1544172/29974620-70de739c-8f6e-11e7-8322-e7532996ceac.png)

その場合は、`const USER_DEFAULT_OPTION_VALUE = "foo"`的なのをjsファイルに書いてもらって、
qiita-team-extension側では`typeof USER_DEFAULT_OPTION_VALUE != 'undefined'`みたいなチェックを使って外部ファイルの定数を使うイメージです。

**Comment by nalabjp** [comment]
ハードコードだとTampermonkeyがユーザースクリプトを自動更新したときに設定し直す手間があるので、
外部ファイルとしてgistから読み込むとかっていうのは良いかもしれないですね。
最初の設定がちょっと手間だけど、セキュリティの観点だとこの辺が限界なのかもしれないなぁと思いました🤔

**Comment by yasulab** [comment]
調査ありがとうございます! 😸 「グループ名が分かってしまう」というだけで、特にクリティカルな問題が発生するわけではないと思うので、一旦はグループ名を直接書いてしますね ;) 書き込んだらこちらの Issue は close します! ✅

**Comment by yasulab** [comment]
🤔.oO(別件ですが、今回グループ名のデフォルト値を決めた方法と同様の方法で、 #3 ができるんじゃないかなぁと考えています。デフォルト値を共同編集に固定できると嬉しいので ><)
