### ISSUE TITLE
デフォルトの編集権限を「共同編集」にしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/qiita-team-extension#3]
esa.io の良いところはデフォルトの設定が「誰でも編集できる」状態になっていることかなぁと考えています🤔

Qiita:Team にも似た機能 (共同編集) があるんですが、これがデフォルトではないんですよね 💦  デフォルトが共同編集になっていても author 情報は残るので、であればデフォルトは「共同編集」でいいんじゃないかなと感じています 🔧 💨 

Qiita:Team では現在「共同編集」をデフォルト値に設定できませんが、もしかしたら exntension として実装できるかも...? と思って Issue にあげてみました 💭 cc/ @nalabjp さん

**Comment by hanachin** [comment]
#4 で実装されてそうです 🎉  とじちゃいますね。
